#cloud-config
package_update: true
package_upgrade: true
packages:
  - ufw
runcmd:
  - ufw enable
  - ufw allow 22
  - curl https://packages.hetzner.com/hcloud/deb/hc-utils_0.0.3-1_all.deb -o /tmp/hc-utils_0.0.3-1_all.deb -s
  - apt install /tmp/hc-utils_0.0.3-1_all.deb && rm /tmp/hc-utils_0.0.3-1_all.deb
