version: '3'

services:
  db:
    image: postgres:${POSTGRES_TAG:-latest}
    shm_size: 1gb
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    restart: unless-stopped

  web:
    image: concourse/concourse:latest
    command: web
    depends_on: [db]
    ports: [8080:8080]
    restart: unless-stopped
    volumes:
    - "./keys:/concourse-keys"
    environment:
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-keys/session_signing_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-keys/worker_key
      CONCOURSE_TSA_HOST_KEY: /concourse-keys/tsa_host_key
      CONCOURSE_LOG_LEVEL: error
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: https://ci.taydev.net
      CONCOURSE_CLUSTER_NAME: ci
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      CONCOURSE_GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      CONCOURSE_MAIN_TEAM_GITHUB_USER: taylorsilva

  worker:
    image: concourse/concourse:latest
    command: worker
    privileged: true
    restart: unless-stopped
    depends_on: [web]
    volumes: ["./keys:/concourse-keys"]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_PUBLIC_KEY: /concourse-keys/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /concourse-keys/worker_key
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE: "true"

