version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # uid and gid should match that of config and cache dir's
    user: 1000:1000
    group_add:
      # should be id of the render group in /etc/group
      - 109
    network_mode: "host"
    environment:
      # have to declare because I migrated from local installation to docker
      JELLYFIN_CACHE_DIR: /cache
      JELLYFIN_CONFIG_DIR: /config/config
      JELLYFIN_DATA_DIR: /config
      JELLYFIN_LOG_DIR: /config/log
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /media:/media
    devices:
      # VAAPI devices for hardware acceleration
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: "unless-stopped"
