version: "3.7"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: 0.75
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      -  ./config:/config
      - /home/taylor/Downloads:/downloads
    restart: unless-stopped
