services:
  transmission-openvpn:
    # https://haugene.github.io/docker-transmission-openvpn/
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/taylor/Downloads:/data
    deploy:
      resources:
        limits:
          cpus: 0.6
    environment:
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: ca_ontario
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      LOCAL_NETWORK: 100.64.0.0/10
      TRANSMISSION_WEB_UI: flood-for-transmission
      PUID: 1000
      GUID: 1000
      TZ: America/Toronto
    logging:
      driver: "local"
      options:
        max-size: "100m"
    ports:
      - 9091:9091
    devices: #Fix permission issues with IPv6
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
